#./statistics_for_ship.perl --ship=Corwin > Corwin.out
#./statistics_for_ship.perl --ship=Jeannette > Jeannette.out
#./statistics_for_ship.perl --ship=Manning > Manning.out
#./statistics_for_ship.perl --ship=Rodgers > Rodgers.out
#./statistics_for_ship.perl --ship='Unalga (II)' > Unalga_II.out
#./statistics_for_ship.perl --ship=Yukon > Yukon.out
#./statistics_for_ship.perl --ship=Bear > Bear.out
./statistics_for_ship.perl --ship=Thetis > Thetis.out
#./statistics_for_ship.perl --ship=Rush > Rush.out
#./statistics_for_ship.perl --ship=Concord > Concord.out
#./statistics_for_ship.perl --ship=Pioneer > Pioneer.out
#./statistics_for_ship.perl --ship=Perry > Perry.out
#./statistics_for_ship.perl --ship=Vicksburg > Vicksburg.out
./statistics_for_ship.perl --ship=Yorktown > Yorktown.out
./statistics_for_ship.perl --ship=Patterson > Patterson.out
./statistics_for_ship.perl --ship='Unalga (I)' > Unalga_I.out
./statistics_for_ship.perl --ship='Jamestown (1844)' > Jamestown_1844.out
#./statistics_for_ship.perl --ship='Jamestown (1866)' > Jamestown_1866.out
#./statistics_for_ship.perl --ship='Jamestown (1879)' > Jamestown_1879.out
./statistics_for_ship.perl --ship='Jamestown (1886)' > Jamestown_1886.out
#./statistics_for_ship.perl --ship='Albatross (1884)' > Albatross_1884.out
./statistics_for_ship.perl --ship='Albatross (1890)' > Albatross_1890.out
./statistics_for_ship.perl --ship='Albatross (1900)' > Albatross_1900.out

